config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'parser#index'

  namespace :parser do
    get 'index'
    post 'process_file'
    get 'results'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord

  has_many :orders

  validates_presence_of :name

end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :merchant

  has_and_belongs_to_many :order

  validates_numericality_of :base_price, greater_than_or_equal_to: 0

  validates_presence_of :base_price
  validates_presence_of :merchant
  validates_presence_of :description

end

app/models/merchant.rb
class Merchant < ApplicationRecord

  has_many :items

  validates_presence_of :name

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :client

  has_and_belongs_to_many :items

  validates_presence_of :client
  validates_presence_of :items

  def self.all_total_incoming
    Order.all.to_a.sum(&:total)
  end

  def total
    items.sum(:base_price)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :set_locale

  def set_locale
    I18n.locale = http_accept_language.compatible_language_from(I18n.available_locales)
  end

end

app/controllers/parser_controller.rb
class ParserController < ApplicationController

  before_action :verify_file, only: %i(process_file)

  def index; end

  def process_file
    result = TabFileParser.new(file_path: @file_path).call
    if result.success?
      flash[:notice] = I18n.t('views.parser.file_processed')
      redirect_to parser_results_path
    else
      flash[:danger] = result.errors
      redirect_to parser_index_path
    end
  end

  def results
    @clients = Client.all
    @orders = Order.all
    @merchants = Merchant.all
    @items = Item.all
  end

  private

  def verify_file
    @file_path = params[:parser][:input_file].tempfile
    return if @file_path.present?
    flash[:warning] = I18n.t('views.parser.not_sent')
    redirect_to parser_index_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |_key, message| %>
  <%= content_tag :div, message %>
<% end %>

app/views/layouts/_footer.html.erb
<style>
  .footer {
    position: fixed;
    left: 0;
    bottom: 0;
    width: 100%;
    background-color: gray;
    color: white;
    text-align: center;
  }
</style>

<div class="footer">
  <p><%= I18n.t('views.application.developed_by', name: 'Rodrigo Pedro Felipe Marques') %></p>
  <p><a href="mailto:rodrigomarques1993@gmail.com">rodrigomarques1993@gmail.com</a></p>
  <p><a href="https://www.linkedin.com/in/rodrigopedromarques/">LinkedIn</a></p>
</div>

app/views/layouts/_links_menu.html.erb
<ul>
  <%= link_to I18n.t('views.application.links.home'), parser_index_path %>
  <%= link_to I18n.t('views.application.links.results'), parser_results_path %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= I18n.t('views.application.project_title') %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/flash' %>
    <%= render 'layouts/links_menu' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/parser/index.html.erb
<title>Meu form querido</title>

<section>

</section>

<section>
  <%= form_for :parser, url: parser_process_file_path, html: { method: :post } do |form| %>
    <div>
      <%= form.file_field :input_file, required: true %>
    </div>

    <%= form.submit I18n.t('views.parser.send_file') %>
  <% end %>
</section>

app/views/parser/results.html.erb
<h1><%= I18n.t('views.parser.sales_results') %></h1>

<div><%= I18n.t('views.parser.total_clients', number_of_clients: @clients.size) %></div>

<div><%= I18n.t('views.parser.total_merchants', number_of_merchants: @merchants.size) %></div>

<div><%= I18n.t('views.parser.total_items', number_of_items: @items.size) %></div>

<div><%= I18n.t('views.parser.total_orders', number_of_orders: @orders.size) %></div>

<div><%= I18n.t('views.parser.total_orders_incoming', total: Order.all_total_incoming.to_f.to_s.gsub('.', ',')) %></div>